githubRepoOwner: classner
githubRepoName: vcstest
githubHost: github.com
githubRemote: origin
githubBranch: main
requireChecks: false
requireApproval: false
mergeMethod: rebase
mergeQueue: false
forceFetchTags: false
showPrTitlesInStack: false
branchPushIndividually: false
